### ISSUE TITLE
SharpClipboard crashes when copying from Outlook overview

### ISSUE THREAD

**Issue by satyris** [Willy-Kimura/SharpClipboard#2] opened 2019-03-12 15:30 UTC
![outlook](https://user-images.githubusercontent.com/48486136/54212393-23c6b200-44e3-11e9-8d1a-83cf0042124e.png)

When copying from Outlook overview, SharpClipboard crashes.

System.Runtime.InteropServices.COMException (0x800401D3): Data on clipboard is invalid. (Ausnahme von HRESULT: 0x800401D3 (CLIPBRD_E_BAD_DATA))
System.Runtime.InteropServices.COMException (0x800401D3): Data on clipboard is invalid. (Ausnahme von HRESULT: 0x800401D3 (CLIPBRD_E_BAD_DATA))
System.ArgumentNullException: The value must not be NULL.
Parametername: collection
   bei System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
An unhandled exception of type 'System.ArgumentNullException' occurred in mscorlib.dll
The value must not be NULL.

**Comment by Willy-Kimura** [comment] 2019-03-13 07:39
I've managed to reproduce the same error. 
Will be planning a fix for it sooner...

**Comment by Willy-Kimura** [comment] 2019-03-16 22:17
The issue is now fixed in `v3.0.0`.

Items such as **Outlook emails** will now be categorized as complex objects (blobs), and will be of type `SharpClipboard.ContentTypes.Other`. You can however display such items using the property `ClipboardText` if you don't need to parse them at all. Feel free to update and try now.

**Closed as completed** 2019-03-17 18:00 UTC
Labels: good first issue

**Comment by satyris** [comment] 2019-05-13 08:12
Thank you so much for the fix. It works for me.

**Comment by Willy-Kimura** [comment] 2019-05-13 13:31
Great!
